### ISSUE TITLE
Images served with wrong content-type header

### ISSUE THREAD

**Issue by irvinebroque** [awesomebox/awesomebox#5]
With a PNG served from `/content/images', the following request doesn't set the content-type headers properly:

http://0.0.0.0:8000/images/awesomebox-transparent-bg.png

![screen shot 2013-08-03 at 5 36 33 pm](https://f.cloud.github.com/assets/1221592/906410/fad8e356-fc9d-11e2-855a-9790454dac70.png)

This prevents images from being served from Awesomebox.

**Comment by irvinebroque** [comment]
Experiencing something similar trying to serve custom fonts - but in this case, the content-type does appear to be sent properly.

Pretty sure both of these are related to the 0.0.15 to 0.0.16 changes, since functionality was working fine beforehand.

**Comment by irvinebroque** [comment]
Interestingly, cloud.typography (typography.com) seems to have the exact same issue with their own build process to serve static assets - when I change a config on there, for the first 30 seconds the content-type isn't specified correctly.

They're a new product and I actually wouldn't be surprised if they're also using node & express.

**Comment by mattinsler** [comment]
Fixed: 5d40841
