### ISSUE TITLE
Liquid Templating Engine Support

### ISSUE THREAD

**Issue by irvinebroque** [awesomebox/awesomebox#7]
Jekyll's standard templating engine is [Liquid](https://github.com/Shopify/liquid), which consolidate.js does not support.

Ran into this today trying to port over the Bootstrap Docs, which are generated using Jekyll.

**Comment by mattinsler** [comment]
Try out http://paularmstrong.github.io/swig/ or http://archan937.github.io/templayed.js/

One of those should be practically the same thing. There's an interesting liquid port at https://github.com/sirlantis/liquid-node that I can try to use too.

**Comment by mattinsler** [comment]
There's also https://npmjs.org/package/liquify

**Comment by irvinebroque** [comment]
Thanks - didn't realize there was so much overlap between those.

One thing I've found so far in trying to move things over is that so much of the work comes from translating the standard jekyll logic into Awesomebox, like `page.title` or `page.base_url`. This showed two things:

1) A "simple" Jekyll site is complicated and a lot of the logic has to do with setting prod vs. local variables.
2) It's WAY easier to compile down the Jekyll into static files, and then port it to Awesomebox. Nice validation of the fuck_grunt concept. This is probably progressively less true as a site gets bigger, but in which case, there's a larger sample set to "learn" against to reconstruct the structure. Really cool how deconstructing logic-free files is easier for both humans and machines than trying to actually parse the original logic.

**Comment by irvinebroque** [comment]
This is not a problem.
